---
- name: Install WordPress, MariaDB, Firewalld, Nginx, and PHP-FPM
  hosts: tag_Name_WP_Candidate_65359de9
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - firewalld
    - mariadb
    - nginx
    - php-fpm
    - wordpress
