---
# This playbook will install Firewalld.

- name: Install Firewalld package
  yum: name=firewalld state=installed
   
- name: Start firewalld Service
  service: name=firewalld state=started enabled=yes
